apiVersion: v1
kind: Service
metadata:
  name: ext-authz-server
  namespace: foo
  labels:
    app: ext-authz-server
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 9000
    targetPort: 9000
  selector:
    app: ext-authz-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-authz-server
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-server
  template:
    metadata:
      labels:
        app: ext-authz-server
      annotations:
        sidecar.istio.io/componentLogLevel: "rbac:debug,jwt:debug,filter:debug"
    spec:
      containers:
      - image: gcr.io/ymzhu-istio/ext-authz-server:0.2
        imagePullPolicy: IfNotPresent
        name: ext-authz-server
        ports:
        - containerPort: 8000
        - containerPort: 9000
---
